include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore

linter:
  rules:
    prefer_single_quotes: true